- src
  - controllers
    - tokenController.ts
  - database
    - postgres.ts
    - redis.ts
  - models
    - cardToken.ts
  - utils
    - luhnAlgorithm.ts
  - app.ts
- tests
  - tokenController.test.ts
- package.json
- tsconfig.json
- README.MD
